### PR TITLE
Added CustomSmoothies and ReadSmoothieFile paramaterisation

### PR DESCRIPTION
**Pull request by peterlitman**
The CustomSmoothie module prints the ingredients menu (which I have added here too), allows the user to add their choice of ingredients from it to their custom smoothie and finally returns a string describing that custom smoothie. It is ready to be called by CustomerOrder

Could maybe benefit from some error handling: currently if type other than int is entered eg on line 22 and 30 the program will crash

### CODE REVIEW

**Review by MillieM27 — CHANGES_REQUESTED** [review]
looking good Peter! Only thing to comment on is the error handling as you said - requesting this be added to accommodate unexpected inputs, other than that code appears fine to me

**Review by GregRobertson96 — CHANGES_REQUESTED** [review]
Looking good. Only need to implement error handlings as Millie already mentioned.

**Review by 2608132H — APPROVED** [review]
Looks good to me.

**Review by GregRobertson96 — APPROVED** [review]
Looks good.

**Review by MillieM27 — APPROVED** [review]
looks good!

**Pull request merged**
