### PR TITLE
Added changes to customer order for reviewing, removing and order tot…

### PR DESCRIPTION
**Pull request by Jordan3421**
Added various changes to meet the minimal viable product.
- Order Review
- Edit Items
- Total order amount

### CODE REVIEW

**Review by GregRobertson96 — APPROVED** [review]
Looks good.

**Review by peterlitman — APPROVED** [review]
Excellent, now our MVP is met

**Review by MillieM27 — APPROVED** [review]
looks good - looks like we have met our minimum viable product!

**Review by 2608132H — COMMENTED** [review]
Looks good to me.  Also the removal of Price- on the prices will make it easier for formatting

**Pull request merged**
